import { Concierto } from "./concierto.js";
export var conciertos = [
    new Concierto(1, "Eras Tour", "The Eras Tour es la sexta gira de conciertos en curso de la cantautora estadounidense Taylor Swift. La gira, que consta de 152 espectáculos en los cinco continentes, comenzó el 17 de marzo de 2023 en Glendale, Arizona , Estados Unidos, y concluirá el 8 de diciembre de 2024 en Vancouver , Canadá. Con un impacto cultural global , Eras Tour se convirtió en la primera gira en superar los mil millones de dólares en ingresos, que la convierte en la gira con mayor recaudación de todos los tiempos.", "https://i.pinimg.com/564x/41/17/ea/4117eaa67ee2a873836eb7b9d1813ca6.jpg", ["Cruel Summer", "The Man", "The Archer"], ["Fearless", "You Belong With Me", "All Too Well"], ["Willow", "Marjorie", "Tolerate It"], ["Ready For It?", "Delicate", "Look What You Made Me Do"], ["22", "We Are Never Ever Getting Back Together", "All Too Well (10 Minute Version)"], ["Seven", "August", "Cardigan"], ["Style", "Blank Space", "Bad Blood"], ["Midnight Rain", "Bejeweled", "Mastermind"], "https://i.pinimg.com/564x/41/fb/2e/41fb2e9f4dd92fb255a4d9d884ce9ffc.jpg", "https://i.pinimg.com/736x/ed/4f/cd/ed4fcd2734f660439dfd56b333d122bd.jpg", "El vestuario de Swift en el Eras Tour fue objeto de una amplia cobertura mediática.", "El vestido de fiesta de tul con lentejuelas que Murad diseñó para el acto Speak Now requirió más de 350 horas de trabajo manual en el taller .", 1200000000 // dineroRecaudado
    ),
    new Concierto(2, "Love On Tour", "Love On Tour es la gira de conciertos global de Harry Styles, que comenzó en 2021 para promocionar su álbum 'Fine Line'. Esta gira incluye múltiples paradas en América del Norte, Europa y Asia, destacándose por su energía y la conexión íntima con el público.", "https://i.pinimg.com/564x/19/ba/1c/19ba1ce78792d062f820191cfef9e61c.jpg", ["Watermelon Sugar", "Adore You", "Golden"], ["Cherry", "Falling", "To Be So Lonely"], ["She", "Sunflower, Vol. 6", "Canyon Moon"], ["Treat People With Kindness", "Fine Line", "Lights Up"], ["Sign of the Times", "Kiwi", "Only Angel"], ["Two Ghosts", "Sweet Creature", "Meet Me in the Hallway"], ["Carolina", "Woman", "From the Dining Table"], ["As It Was", "Late Night Talking", "Music For a Sushi Restaurant"], "https://i.pinimg.com/564x/1b/a7/d6/1ba7d62977bb876a56c376760184aa63.jpg", "https://i.pinimg.com/564x/05/01/02/050102e049a2b52ac4b16c116ac5a44a.jpg", "El estilo de Harry Styles en el Love On Tour ha sido destacado por su eclecticismo y su influencia retro, reflejando la estética de los años 70 y 80.", "Los trajes usados por Styles han sido diseñados por nombres notables en la moda, incluyendo trajes personalizados que han capturado la atención del público y de la prensa especializada.", 500000000 // dineroRecaudado
    ),
    new Concierto(3, "Sweetener World Tour", "La Sweetener World Tour es la cuarta gira de conciertos de Ariana Grande, promocionando sus álbumes 'Sweetener' y 'Thank U, Next'. La gira es conocida por sus impresionantes escenarios y efectos visuales, así como por la potente voz de Grande.", "https://link-to-your-image.jpg", ["No Tears Left to Cry", "God is a Woman", "Breathin"], ["7 rings", "Thank U, Next", "Break Up With Your Girlfriend, I'm Bored"], ["Dangerous Woman", "Side to Side", "Into You"], ["Love Me Harder", "One Last Time", "The Way"], ["R.E.M", "Be Alright", "Sweetener"], ["Positions", "34+35", "POV"], ["Motive", "Just Like Magic", "Off the Table"], ["My Everything", "The Light is Coming", "Everytime"], "https://i.pinimg.com/236x/bc/b1/9e/bcb19e85ebaf071783601e48358805cc.jpg", "https://link-to-your-image.jpg", "La estética del tour refleja una combinación de dulzura y fuerza, con elementos de diseño inspirados en el espacio y la espiritualidad.", "El vestuario en el tour destaca por ser tanto futurista como retro, con un enfoque especial en los detalles brillantes y metálicos.", 650000000 // dineroRecaudado
    ),
    new Concierto(4, "SOUR Tour", "El SOUR Tour es la primera gira de conciertos de Olivia Rodrigo, promocionando su álbum debut 'SOUR'. Esta gira ha sido celebrada por su intimidad y la energía emotiva, conectando profundamente con los fans a través de letras introspectivas y actuaciones personales.", "https://link-to-your-image.jpg", ["drivers license", "traitor", "good 4 u"], ["deja vu", "brutal", "enough for you"], ["happier", "jealousy, jealousy", "favorite crime"], ["hope ur ok", "1 step forward, 3 steps back", "SOUR"], ["All I Want", "Granted", "The Rose Song"], ["Apocalyptic Crush", "Gross", "payback"], ["Vampire", "Prelude", "The Best Part"], ["Get Into It (Yuh)", "Shut Down", "Happy and Healthy"], "https://i.pinimg.com/564x/f7/ec/9f/f7ec9fc86235587c3dd8a4db24b3e935.jpg", "https://link-to-your-image.jpg", "El estilo de Olivia en el tour se caracteriza por una mezcla de estilos de rock alternativo y pop, con un toque juvenil y fresco.", "Los outfits están llenos de referencias a la cultura pop de los años 90 y 2000, con un enfoque en la comodidad y el estilo personal.", 300000000 // dineroRecaudado
    ),
    new Concierto(5, "Melodrama World Tour", "La Melodrama World Tour es la segunda gira de conciertos de Lorde, promocionando su álbum 'Melodrama'. La gira es conocida por su estética minimalista y performances emotivas que resaltan las letras profundas de Lorde.", "https://link-to-your-image.jpg", ["Green Light", "Sober", "Homemade Dynamite"], ["Liability", "Supercut", "Perfect Places"], ["Writer in the Dark", "The Louvre", "Hard Feelings"], ["Loveless", "Sober II (Melodrama)", "Royals"], ["Team", "Buzzcut Season", "Ribs"], ["Yellow Flicker Beat", "Magnets", "Tennis Court"], ["400 Lux", "Swingin Party", "A World Alone"], ["Solar Power", "Stoned at the Nail Salon", "Mood Ring"], "https://i.pinimg.com/564x/d2/b5/21/d2b521bd9e18df6a8f81e19215297b87.jpg", "https://link-to-your-image.jpg", "El enfoque de Lorde en el diseño de sus shows en vivo combina lo surreal con lo personal, creando una experiencia visual y sonora única.", "Sus vestidos, a menudo fluidos y etéreos, complementan la naturaleza introspectiva de su música y performances.", 220000000 // dineroRecaudado
    ),
    new Concierto(6, "LA to the Moon Tour", "La LA to the Moon Tour es una gira de Lana Del Rey que promociona su álbum 'Lust for Life'. La gira destaca por su estilo retro y la atmósfera nostálgica que evoca los paisajes sonoros de Lana, con una mezcla de canciones antiguas y nuevas.", "https://link-to-your-image.jpg", ["Love", "Lust for Life", "13 Beaches"], ["Cherry", "White Mustang", "Summer Bummer"], ["Groupie Love", "In My Feelings", "Coachella - Woodstock In My Mind"], ["God Bless America - And All the Beautiful Women in It", "When the World Was at War We Kept Dancing", "Beautiful People Beautiful Problems"], ["Music To Watch Boys To", "High By The Beach", "Freak"], ["Art Deco", "Salvatore", "The Blackest Day"], ["Ride", "American", "Cola"], ["Video Games", "Born to Die", "Blue Jeans"], "https://i.pinimg.com/564x/63/06/68/6306683f9a5880c394432bde51b94562.jpg", "https://link-to-your-image.jpg", "Lana Del Rey en el tour ofrece un escape visual a una era pasada, con una estética fuertemente influenciada por los años 60 y 70.", "Sus trajes, con un enfoque en la elegancia y la simplicidad, reflejan la melancolía y el romance de su música.", 180000000 // dineroRecaudado
    ),
];
export var data = conciertos.map(function (concierto) { return new Concierto(concierto.id, concierto.titulo, concierto.descripcion, concierto.imagenPrincipal, concierto.setList1, concierto.setList2, concierto.setList3, concierto.setList4, concierto.setList5, concierto.setList6, concierto.setList7, concierto.setList8, concierto.imagenModa1, concierto.imagenModa2, concierto.textoModa1, concierto.textoModa2, concierto.ventas); });
